const data = [
  {
    id: "a",
    title: "Turkish champions won’t give Nwakaeme ‘high’ 3-year contract",
    imgUrl: "./avatar.png",
    type: "full",
    commentCount: "76",
    likes: "50",
    category: "Sports",
    region: "USA",
    views: "200",
    author: "Philip Maxwell",
    publicationDate: "Jan 14, 2022",
    description:
      "\t\t\tTrabzonspor chairman Ahmet Agaoglu has revealed that his club have offered Anthony Nwakaeme what they are capable of paying and waiting for the Nigerian forward to respond. He said the offer made to Nwakaeme will make him the highest paid at the club, but the team cannot afford the number of years demanded by the striker. \n\n\t\t\t“We offered Anthony Nwakaeme the highest wage we could give. The three-year contract was high for us. He is a very valuable player,” he said. The 33-year-old striker scored 13 goals in 30 league games as Trabzonspor emerged champions in Turkey.",
    comments: [
      {
        id: "1",
        body: "First comment",
        username: "Jack",
        userId: "1",
        parentId: null,
        createdAt: "2022-06-10T18:00:33.010+02:00",
      },
      {
        id: "2",
        body: "First comment first child",
        username: "Sparrow",
        userId: "2",
        parentId: "1",
        createdAt: "2022-05-10T18:00:33.010+02:00",
        replyTo: "Jack",
      },
      {
        id: "3",
        body: "Second comment",
        username: "Van Dick",
        userId: "3",
        parentId: null,
        createdAt: "2022-06-10T18:00:33.010+02:00",
      },
      {
        id: "4",
        body: "Second comment first child",
        username: "Jack",
        userId: "1",
        parentId: "3",
        createdAt: "2022-05-10T18:00:33.010+02:00",
        replyTo: "Van Dick",
      },
      {
        id: "5",
        body: "Second comment second child",
        username: "Jack",
        userId: "1",
        parentId: "3",
        createdAt: "2022-06-11T18:00:33.010+02:00",
        replyTo: "Van Dick",
      },
      {
        id: "6",
        body: "Third comment child",
        username: "Jack",
        userId: "1",
        parentId: null,
        createdAt: "2022-06-11T18:00:33.010+02:00",
      },
      {
        id: "7",
        body: "Second comment third child",
        username: "Jack",
        userId: "1",
        parentId: "3",
        createdAt: "2022-06-11T18:00:33.010+02:00",
        replyTo: "Van Dick",
      },
    ],
  },
];

export default data;
